# Site settings
title: *folio
email: ambarish.ganguly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  
url:  "http://machinelearningfun.github.io"
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Includes & excludes
include: ['_pages']

kramdown:
  input: GFM

# Pagination
paginate: 6
paginate_path: "blog/page:num"


collections:


 # Gems
plugins:
  - jekyll-paginate


